= Customized WiFi library for the Adafruit Feather M0+ WINC1500 =

Intent: upgrade the WINC1500 (B) from 19.5.2 to 19.6.1, and customize the WiFi101 library to provide access to the newly supported WPA2 Enterprise EAP authentication functionality.

No extra hardware required (just PC laptop and Feather M0+ WINC1500)

Adafruit_WINC1500 (~2yrs old) == Ada
WiFi101 0.15.2 == WiFi
Microchip(Atmel)'s drivers 


== References ==

http://ww1.microchip.com/downloads/en/DeviceDoc/ATWINC15x0%20Software%20Release%20Notes_9%20Aug%202018.pdf


== Licenses ==

Copyright (c) Arduino LLC. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

====================
